export const dashboardData = {
  navigation: [
    { label: 'Dashboard', path: '/dashboard', icon: '🏠' },
    { label: 'Products', path: '/dashboard/products', icon: '🛒' },
    { label: 'Orders', path: '/dashboard/orders', icon: '📦' },
    { label: 'Marketing', path: '/dashboard/marketing', icon: '📢' },
    { label: 'Ads', path: '/dashboard/ads', icon: '📣' },
    { label: 'Delivery', path: '/dashboard/delivery', icon: '🚚' },
    { label: 'Support', path: '/dashboard/support', icon: '🎫' },
    { label: 'Billing', path: '/dashboard/billing', icon: '💳' },
    { label: 'Settings', path: '/dashboard/settings', icon: '⚙️' },
    { label: 'Notifications', path: '/dashboard/notifications', icon: '🔔' },
    { label: 'Social', path: '/dashboard/social-media', icon: '📱' },
  ],
  header: {
    pills: [],
  },
  revenueData: {
    title: 'Revenue Growth',
    chartData: [
      { month: 'Jan', revenue: 65 },
      { month: 'Feb', revenue: 59 },
      { month: 'Mar', revenue: 80 },
      { month: 'Apr', revenue: 81 },
      { month: 'May', revenue: 56 },
      { month: 'Jun', revenue: 55 },
    ],
  },
  totalSales: {
    title: 'Total Sales',
    emoji: '💰',
    items: [
      { label: 'Today sales', value: '₹2,500' },
      { label: 'This month sales', value: '₹45,000' },
      { label: 'Total sales', value: '₹4,80,000' },
    ],
  },
  totalOrders: {
    title: 'Total Orders',
    emoji: '📦',
    items: [
      { label: 'Total orders', value: '1,248' },
      { label: 'Pending orders', value: '42' },
      { label: 'Completed orders', value: '1,161' },
    ],
  },
  marketingStatus: {
    title: 'Marketing Status',
    emoji: '📢',
    items: [
      { label: 'Active campaigns', value: '6 campaigns live' },
      { label: 'Social media posts', value: '14 scheduled' },
      { label: 'Influencer promotion', value: '3 creators active' },
    ],
  },
  adsPerformance: {
    title: 'Ads Performance',
    emoji: '📊',
    items: [
      { label: 'Ad clicks', value: '8,420' },
      { label: 'Impressions', value: '1,24,800' },
      { label: 'Conversions', value: '386' },
    ],
  },
  websiteVisitors: {
    title: 'Website Visitors',
    emoji: '🌐',
    items: [
      { label: 'Today visitors', value: '1,120' },
      { label: 'Monthly visitors', value: '27,450' },
    ],
  },
  deliveryStatus: {
    title: 'Delivery Status',
    emoji: '🚚',
    items: [
      { label: 'Orders shipped', value: '79' },
      { label: 'Orders delivered', value: '61' },
      { label: 'Orders in transit', value: '18' },
    ],
  },
  notifications: {
    title: 'Notifications',
    emoji: '🔔',
    items: [
      { label: 'New order', value: 'Order #1042 placed 8 min ago' },
      { label: 'Marketing update', value: 'Spring campaign crossed 5k reach' },
      { label: 'Payment reminder', value: 'Subscription renews in 3 days' },
    ],
  },
  quickActions: {
    title: 'Quick Actions',
    emoji: '⚡',
    actions: [
      'Add Product',
      'Create Campaign',
      'Contact Support',
      'Upgrade Plan',
    ],
  },
  products: {
    header: {
      title: 'Products',
      description:
        'Manage product catalog, inventory, media and quick edits from one place.',
    },
    filters: [
      { label: 'Search by name', value: 'Classic Cotton Tee' },
      { label: 'Filter by category', value: 'Apparel' },
      { label: 'Filter by stock status', value: 'Active' },
    ],
    items: [
      {
        image: '👕',
        name: 'Classic Cotton Tee',
        category: 'Apparel',
        price: '₹899',
        stock: '128',
        status: 'Active',
        statusStyle: 'active',
        sku: 'SKU-TEE-001',
      },
      {
        image: '🎒',
        name: 'Travel Daypack',
        category: 'Accessories',
        price: '₹1,799',
        stock: '18',
        status: 'Low stock',
        statusStyle: 'warning',
        sku: 'SKU-BAG-019',
      },
      {
        image: '⌚',
        name: 'Urban Smart Watch',
        category: 'Electronics',
        price: '₹4,999',
        stock: '0',
        status: 'Out of stock',
        statusStyle: 'out',
        sku: 'SKU-WAT-202',
      },
    ],
    form: {
      fields: [
        { label: 'Product Name', value: 'Classic Cotton Tee' },
        {
          label: 'Product Description',
          value: 'Soft premium cotton t-shirt with breathable fabric and all-day comfort.',
          type: 'textarea',
          large: true,
        },
        { label: 'Product Price', value: '₹899' },
        { label: 'Product Category', value: 'Apparel' },
        { label: 'Product Images Upload', value: 'front.jpg, back.jpg' },
        { label: 'Stock Quantity', value: '128 units' },
        { label: 'SKU / Product Code', value: 'SKU-TEE-001' },
        { label: 'Variants (Size / Color)', value: 'S, M, L / Black, White' },
      ],
    },
    media: [
      { label: 'Images', value: '12 assets uploaded' },
      { label: 'Videos', value: '3 promo clips ready' },
    ],
    inventory: [
      { label: 'Total stock', value: '462 units' },
      { label: 'Low stock alert', value: '7 products' },
      { label: 'Out of stock warning', value: '2 products' },
    ],
    performance: [
      { label: 'Product sales', value: 'Future ready block' },
      { label: 'Views', value: 'Future ready block' },
      { label: 'Conversion rate', value: 'Future ready block' },
      { label: 'Editable fields', value: 'Price, description, images, stock' },
    ],
  },
  orders: {
    header: {
      title: 'Orders',
      description:
        'Track order lifecycle, payment health, delivery status and order support actions from one workspace.',
    },
    filters: [
      { label: 'Pending orders', value: '18 orders' },
      { label: 'Delivered orders', value: '94 orders' },
      { label: 'Cancelled orders', value: '6 orders' },
      { label: 'Date wise', value: '14 Mar 2026' },
    ],
    search: [
      { label: 'Search by order ID', value: 'ORD-1042' },
      { label: 'Search by customer name', value: 'Aarav Mehta' },
    ],
    exportOptions: ['Export CSV', 'Export Excel'],
    items: [
      {
        id: 'ORD-1042',
        customer: 'Aarav Mehta',
        product: 'Classic Cotton Tee',
        quantity: '2',
        totalPrice: '₹1,798',
        paymentStatus: 'Paid',
        paymentStyle: 'active',
        orderStatus: 'Processing',
        orderStyle: 'info',
        date: '14 Mar 2026',
      },
      {
        id: 'ORD-1038',
        customer: 'Riya Sharma',
        product: 'Travel Daypack',
        quantity: '1',
        totalPrice: '₹1,799',
        paymentStatus: 'Cash on Delivery',
        paymentStyle: 'warning',
        orderStatus: 'Shipped',
        orderStyle: 'warning',
        date: '13 Mar 2026',
      },
      {
        id: 'ORD-1031',
        customer: 'Kabir Jain',
        product: 'Urban Smart Watch',
        quantity: '1',
        totalPrice: '₹4,999',
        paymentStatus: 'Failed',
        paymentStyle: 'out',
        orderStatus: 'Cancelled',
        orderStyle: 'out',
        date: '12 Mar 2026',
      },
    ],
    statuses: [
      { label: 'Pending', value: '12 orders' },
      { label: 'Processing', value: '18 orders' },
      { label: 'Shipped', value: '9 orders' },
      { label: 'Delivered', value: '94 orders' },
      { label: 'Cancelled', value: '6 orders' },
    ],
    paymentStatuses: [
      { label: 'Paid', value: '108 orders' },
      { label: 'Pending', value: '11 orders' },
      { label: 'Failed', value: '3 orders' },
      { label: 'Cash on Delivery', value: '17 orders' },
    ],
    details: {
      customerName: 'Aarav Mehta',
      phoneNumber: '+91 98765 43210',
      address: '22 Lake View Residency, Andheri West, Mumbai',
      productDetails: 'Classic Cotton Tee, Black, Size M, Qty 2',
      priceBreakdown: 'Subtotal ₹1,798, Shipping ₹80, Tax ₹144',
      paymentMethod: 'UPI',
    },
    tracking: [
      { label: 'Courier partner', value: 'BlueDart Express' },
      { label: 'Tracking ID', value: 'BDX-34910349' },
      { label: 'Delivery status', value: 'Reached city hub' },
    ],
    actions: ['Cancel Order', 'Refund Request'],
  },
  marketing: {
    header: {
      title: 'Marketing',
      description:
        'Manage campaigns, social content, influencer work and ad results from one clean dashboard.',
    },
    overview: [
      { label: 'Active campaigns', value: '3', icon: '🚀' },
      { label: 'Completed campaigns', value: '12', icon: '✅' },
      { label: 'Total reach', value: '50,000', icon: '🌍' },
      { label: 'Total clicks', value: '8,420', icon: '🖱️' },
    ],
    campaigns: [
      {
        name: 'Summer Glow Launch',
        platform: 'Instagram',
        status: 'Active',
        statusStyle: 'active',
        budget: '₹25,000',
        startDate: '10 Mar 2026',
        endDate: '28 Mar 2026',
      },
      {
        name: 'Retargeting Push',
        platform: 'Facebook',
        status: 'Paused',
        statusStyle: 'warning',
        budget: '₹12,000',
        startDate: '06 Mar 2026',
        endDate: '20 Mar 2026',
      },
      {
        name: 'Search Intent Max',
        platform: 'Google',
        status: 'Completed',
        statusStyle: 'info',
        budget: '₹18,500',
        startDate: '18 Feb 2026',
        endDate: '05 Mar 2026',
      },
    ],
    socialMedia: [
      { label: 'Posts scheduled', value: '18 posts' },
      { label: 'Reels uploaded', value: '7 reels' },
      { label: 'Engagement', value: '4.8k likes / 620 comments' },
    ],
    influencers: [
      {
        name: 'Naina Sharma',
        platform: 'Instagram',
        status: 'Active',
        results: '22k reach / 1.2k clicks',
      },
      {
        name: 'Tech with Arjun',
        platform: 'YouTube',
        status: 'Completed',
        results: '14k views / 310 leads',
      },
      {
        name: 'Style Diary',
        platform: 'Instagram',
        status: 'Active',
        results: '19k reach / 880 saves',
      },
    ],
    adsPerformance: [
      { label: 'Impressions', value: '1,24,800' },
      { label: 'Clicks', value: '8,420' },
      { label: 'Conversions', value: '386' },
      { label: 'Ad spend', value: '₹54,000' },
    ],
    analytics: [
      { label: 'Traffic growth', value: '+18.4% week over week' },
      { label: 'Campaign performance', value: 'Best performer: Summer Glow Launch' },
      { label: 'Audience reach', value: '50k unique users reached' },
    ],
    content: [
      { label: 'Images', value: '22 creatives ready' },
      { label: 'Reels', value: '8 short videos uploaded' },
      { label: 'Ads creatives', value: '11 approved ad sets' },
    ],
  },
  ads: {
    header: {
      title: 'Ads',
      description:
        'Track paid campaigns, audience targeting, creatives and launch new ad campaigns from one place.',
    },
    overview: [
      { label: 'Total Ad Spend', value: '₹5,000', icon: '💰' },
      { label: 'Total Clicks', value: '1,200', icon: '👆' },
      { label: 'Total Impressions', value: '48,000', icon: '👀' },
      { label: 'Conversions', value: '40', icon: '🛒' },
    ],
    campaigns: [
      {
        name: 'Summer Sale Campaign',
        platform: 'Facebook',
        budget: '₹5,000',
        status: 'Active',
        statusStyle: 'active',
        clicks: '1,200',
        conversions: '40',
      },
      {
        name: 'Smartwatch Push',
        platform: 'Google',
        budget: '₹7,500',
        status: 'Paused',
        statusStyle: 'warning',
        clicks: '860',
        conversions: '24',
      },
      {
        name: 'Reel Retarget Blast',
        platform: 'Instagram',
        budget: '₹4,200',
        status: 'Completed',
        statusStyle: 'info',
        clicks: '1,540',
        conversions: '51',
      },
    ],
    targeting: [
      { label: 'Age group', value: '18 - 30' },
      { label: 'Location', value: 'Mumbai, Delhi, Bangalore' },
      { label: 'Interests', value: 'Fashion, Tech, Lifestyle' },
    ],
    graphs: [
      { label: 'Clicks over time', value: 'Up 16% this week' },
      { label: 'Conversions over time', value: 'Steady with weekend spike' },
      { label: 'Ad spend vs revenue', value: '4.3x return on ad spend' },
    ],
    creatives: [
      { label: 'Ad images', value: '14 image creatives uploaded' },
      { label: 'Ad videos', value: '5 short ads ready' },
      { label: 'Ad copy', value: '9 approved copy variants' },
    ],
    controls: ['Pause Ad', 'Resume Ad', 'Change Budget'],
    form: {
      fields: [
        { label: 'Campaign Name', value: 'Summer Sale Campaign' },
        { label: 'Product Selection', value: 'Product A' },
        { label: 'Platform Selection', value: 'Facebook, Instagram' },
        { label: 'Daily Budget', value: '₹500' },
        { label: 'Total Budget', value: '₹5000' },
        { label: 'Age Group', value: '18 - 30' },
        { label: 'Location', value: 'Mumbai' },
        { label: 'Interests', value: 'Fashion, Shopping' },
        { label: 'Image Upload', value: 'sale-banner.jpg' },
        { label: 'Video Upload', value: 'summer-reel.mp4' },
        {
          label: 'Ad Text',
          value: 'Fresh arrivals are live now. Shop the summer drop before it sells out.',
          type: 'textarea',
          large: true,
        },
        { label: 'Start Date', value: '10 June' },
        { label: 'End Date', value: '20 June' },
        { label: 'Call To Action (CTA)', value: 'Shop Now' },
      ],
    },
  },
  delivery: {
    header: {
      title: 'Delivery',
      description:
        'Track shipments, courier partners, delivery progress and issue handling from one dashboard.',
    },
    overview: [
      { label: 'Orders Ready to Ship', value: '5', icon: '📦' },
      { label: 'Orders Shipped', value: '12', icon: '🚚' },
      { label: 'Orders In Transit', value: '9', icon: '🛣️' },
      { label: 'Orders Delivered', value: '30', icon: '✅' },
    ],
    shipments: [
      {
        orderId: 'ORD-1042',
        customerName: 'Aarav Mehta',
        product: 'Classic Cotton Tee',
        courierPartner: 'BlueDart',
        trackingId: 'BDX-34910349',
        deliveryStatus: 'In Transit',
        statusStyle: 'warning',
        estimatedDate: '18 Mar 2026',
      },
      {
        orderId: 'ORD-1038',
        customerName: 'Riya Sharma',
        product: 'Travel Daypack',
        courierPartner: 'Delhivery',
        trackingId: 'DLV-88209322',
        deliveryStatus: 'Shipped',
        statusStyle: 'info',
        estimatedDate: '17 Mar 2026',
      },
      {
        orderId: 'ORD-1024',
        customerName: 'Kabir Jain',
        product: 'Urban Smart Watch',
        courierPartner: 'Shiprocket',
        trackingId: 'SHR-22019311',
        deliveryStatus: 'Delivered',
        statusStyle: 'active',
        estimatedDate: 'Delivered on 14 Mar 2026',
      },
    ],
    trackingSteps: [
      'Order Placed',
      'Shipped',
      'In Transit',
      'Out for Delivery',
      'Delivered',
    ],
    trackingInfo: [
      { label: 'Package location', value: 'Mumbai Sorting Hub' },
      { label: 'Shipment progress', value: 'Reached city hub and moving to local center' },
      { label: 'Delivery date', value: '18 Mar 2026' },
    ],
    courierPartners: ['Shiprocket', 'Delhivery', 'BlueDart', 'DTDC'],
    filters: [
      { label: 'Pending shipments', value: '5 shipments' },
      { label: 'Shipped orders', value: '12 orders' },
      { label: 'Delivered orders', value: '30 orders' },
    ],
    issues: [
      { label: 'Delayed shipment', value: '2 orders running late' },
      { label: 'Failed delivery', value: '1 failed doorstep attempt' },
      { label: 'Return request', value: '3 return pickups pending' },
    ],
  },
  support: {
    header: {
      title: 'Customer Support',
      description:
        'Handle tickets, live chat, support requests and customer help resources from one support hub.',
    },
    ticketForm: {
      fields: [
        { label: 'Subject', value: 'Order delivery delayed' },
        {
          label: 'Description',
          value: 'Customer reports no movement on shipment for 3 days and wants an updated delivery timeline.',
          type: 'textarea',
          large: true,
        },
        { label: 'Order ID (optional)', value: 'ORD-1042' },
        { label: 'File upload', value: 'delay-screenshot.png' },
      ],
    },
    tickets: [
      {
        id: 'TKT-1001',
        subject: 'Order delivery delayed',
        status: 'Open',
        statusStyle: 'warning',
        date: '14 Mar 2026',
      },
      {
        id: 'TKT-1002',
        subject: 'Refund status enquiry',
        status: 'Pending',
        statusStyle: 'info',
        date: '13 Mar 2026',
      },
      {
        id: 'TKT-1003',
        subject: 'Wrong item received',
        status: 'Resolved',
        statusStyle: 'active',
        date: '12 Mar 2026',
      },
    ],
    liveChat: [
      'Website Chat',
      'WhatsApp Support',
      'Chat on WhatsApp',
    ],
    faq: [
      { question: 'Order kaise track kare?', answer: 'Order page ya delivery page me tracking ID se track kare.' },
      { question: 'Refund kaise milega?', answer: 'Support ticket submit kare aur refund request select kare.' },
      { question: 'Delivery time kitna hai?', answer: 'Normal shipping 3-7 working days me complete hoti hai.' },
    ],
    contact: [
      { label: 'Email support', value: 'support@brandstore.com' },
      { label: 'Phone number', value: '+91 98765 00000' },
      { label: 'WhatsApp', value: '+91 98765 11111' },
    ],
    services: [
      'Marketing Request',
      'Ads Campaign Request',
      'Influencer Promotion',
    ],
  },
  billing: {
    header: {
      title: 'Billing',
      description:
        'Manage current plan, payment methods, billing history, invoices and subscription renewal settings.',
    },
    currentPlan: [
      { label: 'Current Plan', value: 'Starter' },
      { label: 'Price', value: '₹2999 / month' },
      { label: 'Plan status', value: 'Active' },
      { label: 'Next billing date', value: '10 July' },
    ],
    plans: ['Starter', 'Growth', 'Pro'],
    paymentMethods: [
      { label: 'UPI', value: 'Enabled' },
      { label: 'Credit Card', value: 'Visa ending 4242' },
      { label: 'Debit Card', value: 'Available' },
      { label: 'Net Banking', value: 'Available' },
      { label: 'Gateway', value: 'Razorpay / Stripe ready' },
    ],
    history: [
      {
        invoiceId: 'INV-2026-0710',
        date: '10 Jul 2026',
        amount: '₹2,999',
        paymentStatus: 'Paid',
        statusStyle: 'active',
      },
      {
        invoiceId: 'INV-2026-0610',
        date: '10 Jun 2026',
        amount: '₹2,999',
        paymentStatus: 'Paid',
        statusStyle: 'active',
      },
      {
        invoiceId: 'INV-2026-0510',
        date: '10 May 2026',
        amount: '₹2,999',
        paymentStatus: 'Pending',
        statusStyle: 'warning',
      },
    ],
    invoices: ['Download PDF Invoice', 'GST Invoice (Future)'],
    autoPayment: [
      { label: 'Auto renew subscription', value: 'Enabled' },
      { label: 'Monthly recurring payment', value: 'Active on 10th of every month' },
    ],
  },
  settings: {
    header: {
      title: 'Settings',
      description:
        'Update profile, business info, security, notifications, payout details and connected channels from one place.',
    },
    profile: {
      fields: [
        { label: 'Name', value: 'Mohit Sharma' },
        { label: 'Email', value: 'mohit@brandstore.com' },
        { label: 'Phone Number', value: '+91 98765 43210' },
        { label: 'Profile Picture', value: 'mohit-profile.png' },
      ],
    },
    business: {
      fields: [
        { label: 'Business Name', value: 'Brand Store Pvt Ltd' },
        { label: 'Business Address', value: '22 Lake View Residency, Mumbai' },
        { label: 'GST Number (optional)', value: '27ABCDE1234F1Z5' },
        { label: 'Business Category', value: 'Fashion & Lifestyle' },
      ],
    },
    security: ['Change Password', 'Enable 2FA'],
    notifications: [
      { label: 'Order notifications', value: 'Enabled' },
      { label: 'Marketing updates', value: 'Enabled' },
      { label: 'Email notifications', value: 'Enabled' },
      { label: 'SMS notifications', value: 'Disabled' },
    ],
    payout: {
      fields: [
        { label: 'Bank account', value: 'HDFC Bank - 2345' },
        { label: 'UPI ID', value: 'brandstore@upi' },
        { label: 'Payout method', value: 'Weekly bank transfer' },
      ],
    },
    socialConnections: ['Instagram', 'Facebook', 'WhatsApp', 'YouTube'],
  },
  notificationsPage: {
    header: {
      title: 'Notifications',
      description:
        'Track all business alerts in one place including orders, marketing, ads, billing, delivery and support updates.',
    },
    newOrders: [
      {
        id: 'notif-order-1',
        message: 'New order received for Product A.',
        time: '2 min ago',
        isUnread: true,
      },
      {
        id: 'notif-order-2',
        message: 'Order #1042 was cancelled by customer.',
        time: '18 min ago',
        isUnread: true,
      },
      {
        id: 'notif-order-3',
        message: 'Order #1038 has been delivered successfully.',
        time: '1 hour ago',
        isUnread: false,
      },
    ],
    marketing: [
      {
        id: 'notif-marketing-1',
        message: 'New marketing campaign "Summer Glow" has started.',
        time: '12 min ago',
        isUnread: true,
      },
      {
        id: 'notif-marketing-2',
        message: 'Influencer promotion with Naina Sharma is now live.',
        time: '36 min ago',
        isUnread: false,
      },
      {
        id: 'notif-marketing-3',
        message: 'Instagram post for weekend sale has been published.',
        time: '3 hours ago',
        isUnread: false,
      },
    ],
    ads: [
      {
        id: 'notif-ads-1',
        message: 'Ad campaign "Summer Sale Campaign" is now active.',
        time: '8 min ago',
        isUnread: true,
      },
      {
        id: 'notif-ads-2',
        message: 'Ad budget for Smartwatch Push is almost complete.',
        time: '42 min ago',
        isUnread: true,
      },
      {
        id: 'notif-ads-3',
        message: 'Weekly ad performance report is ready to review.',
        time: '5 hours ago',
        isUnread: false,
      },
    ],
    billing: [
      {
        id: 'notif-billing-1',
        message: 'Subscription renews in 3 days.',
        time: 'Today',
        isUnread: true,
      },
      {
        id: 'notif-billing-2',
        message: 'Monthly payment of ₹2,999 was successful.',
        time: 'Yesterday',
        isUnread: false,
      },
      {
        id: 'notif-billing-3',
        message: 'Last payment attempt failed for saved card.',
        time: '2 days ago',
        isUnread: true,
      },
    ],
    delivery: [
      {
        id: 'notif-delivery-1',
        message: 'Order #1042 has been shipped.',
        time: '14 min ago',
        isUnread: true,
      },
      {
        id: 'notif-delivery-2',
        message: 'Order #1038 is out for delivery.',
        time: '1 hour ago',
        isUnread: false,
      },
      {
        id: 'notif-delivery-3',
        message: 'Order #1024 has been delivered.',
        time: 'Yesterday',
        isUnread: false,
      },
    ],
    support: [
      {
        id: 'notif-support-1',
        message: 'Support ticket TKT-1002 received a new reply.',
        time: '9 min ago',
        isUnread: true,
      },
      {
        id: 'notif-support-2',
        message: 'Issue for ticket TKT-1003 has been resolved.',
        time: '4 hours ago',
        isUnread: false,
      },
    ],
  },
  socialMedia: {
    header: {
      title: 'Social Media',
      description:
        'Track social media content performance across platforms with overview stats, post insights and growth analytics.',
    },
    overview: [
      { label: 'Total Posts', value: '48', icon: '📝' },
      { label: 'Total Views', value: '50,000', icon: '👀' },
      { label: 'Total Likes', value: '3,200', icon: '❤️' },
      { label: 'Total Comments', value: '640', icon: '💬' },
      { label: 'Followers Growth', value: '+1,250', icon: '📈' },
    ],
    posts: [
      {
        thumbnail: '🎥',
        platform: 'Instagram',
        views: '18,200',
        likes: '1,420',
        comments: '240',
        date: '14 Mar 2026',
        title: 'Weekend Reel Launch',
      },
      {
        thumbnail: '📸',
        platform: 'Facebook',
        views: '12,800',
        likes: '860',
        comments: '130',
        date: '12 Mar 2026',
        title: 'Product Feature Carousel',
      },
      {
        thumbnail: '▶️',
        platform: 'YouTube',
        views: '19,000',
        likes: '920',
        comments: '270',
        date: '10 Mar 2026',
        title: 'Brand Story Video',
      },
    ],
    analytics: [
      { label: 'Views growth', value: '+22% compared to last week' },
      { label: 'Engagement rate', value: '6.4% overall engagement' },
      { label: 'Followers growth', value: '+1,250 new followers this month' },
    ],
  },
}
